// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Context;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", "dbo");

                    b.HasData(
                        new
                        {
                            IdRol = new Guid("240acf13-8d8c-433d-90e0-f9c8b1dea10c"),
                            NombreRol = "ADMIN"
                        },
                        new
                        {
                            IdRol = new Guid("240acf13-8d8c-433d-90e0-f9c8b1dea11c"),
                            NombreRol = "USER"
                        });
                });

            modelBuilder.Entity("webapi.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "dbo");

                    b.HasData(
                        new
                        {
                            UsuarioId = new Guid("240acf13-8d8c-433d-90e0-f9c8b1dea20c"),
                            Email = "Prueba@Gmail.com",
                            NombreUsuario = "Administrador",
                            Password = "$2a$12$lBS.LD7m9wNn8eAtt9LZl.y5Fe/GqTqWrwSEnhiBNhr.DTBGqpt2C",
                            RolId = new Guid("240acf13-8d8c-433d-90e0-f9c8b1dea10c")
                        });
                });

            modelBuilder.Entity("webapi.Models.Usuario", b =>
                {
                    b.HasOne("webapi.Models.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("webapi.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
